export const SHOW_REQUEST_FORM = 'SHOW_REQUEST_FORM';
export const SHOW_HOME = 'SHOW_HOME';
export const SEND_REQUEST_START = 'SEND_REQUEST_START';
export const SEND_REQUEST_FULFILLED = 'SEND_REQUEST_FULFILLED';
export const SEND_REQUEST_ERROR = 'SEND_REQUEST_ERROR';
